/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const VideoId = IDL.Text;
export const QuizResult = IDL.Record({
  'id' : IDL.Nat,
  'score' : IDL.Nat,
  'takenAt' : Timestamp,
  'totalQuestions' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'videoId' : VideoId,
});
export const UserId = IDL.Principal;
export const Language = IDL.Variant({
  'Uzbek' : IDL.Null,
  'Russian' : IDL.Null,
});
export const VocabEntry = IDL.Record({
  'id' : IDL.Nat,
  'sourceVideoId' : VideoId,
  'englishText' : IDL.Text,
  'savedAt' : Timestamp,
  'translationText' : IDL.Text,
});
export const WatchedVideo = IDL.Record({
  'watchedAt' : Timestamp,
  'videoId' : VideoId,
});

export const idlService = IDL.Service({
  'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getUserProfile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'id' : UserId,
            'displayName' : IDL.Text,
            'language' : Language,
          })
        ),
      ],
      ['query'],
    ),
  'getVocabulary' : IDL.Func([], [IDL.Vec(VocabEntry)], ['query']),
  'getWatchedVideos' : IDL.Func([], [IDL.Vec(WatchedVideo)], ['query']),
  'markVideoWatched' : IDL.Func([VideoId], [], []),
  'saveQuizResult' : IDL.Func([VideoId, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveVocabularyWord' : IDL.Func([IDL.Text, IDL.Text, VideoId], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'setLanguagePreference' : IDL.Func([Language], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const VideoId = IDL.Text;
  const QuizResult = IDL.Record({
    'id' : IDL.Nat,
    'score' : IDL.Nat,
    'takenAt' : Timestamp,
    'totalQuestions' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'videoId' : VideoId,
  });
  const UserId = IDL.Principal;
  const Language = IDL.Variant({ 'Uzbek' : IDL.Null, 'Russian' : IDL.Null });
  const VocabEntry = IDL.Record({
    'id' : IDL.Nat,
    'sourceVideoId' : VideoId,
    'englishText' : IDL.Text,
    'savedAt' : Timestamp,
    'translationText' : IDL.Text,
  });
  const WatchedVideo = IDL.Record({
    'watchedAt' : Timestamp,
    'videoId' : VideoId,
  });
  
  return IDL.Service({
    'getQuizResults' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getUserProfile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'id' : UserId,
              'displayName' : IDL.Text,
              'language' : Language,
            })
          ),
        ],
        ['query'],
      ),
    'getVocabulary' : IDL.Func([], [IDL.Vec(VocabEntry)], ['query']),
    'getWatchedVideos' : IDL.Func([], [IDL.Vec(WatchedVideo)], ['query']),
    'markVideoWatched' : IDL.Func([VideoId], [], []),
    'saveQuizResult' : IDL.Func([VideoId, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveVocabularyWord' : IDL.Func([IDL.Text, IDL.Text, VideoId], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'setLanguagePreference' : IDL.Func([Language], [], []),
  });
};

export const init = ({ IDL }) => { return []; };