/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Language = { 'Uzbek' : null } |
  { 'Russian' : null };
export interface PublicUserProfile {
  'id' : UserId,
  'streak' : bigint,
  'displayName' : string,
  'profileImage' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'language' : Language,
  'points' : bigint,
}
export interface QuizResult {
  'id' : bigint,
  'score' : bigint,
  'takenAt' : Timestamp,
  'totalQuestions' : bigint,
  'correctAnswers' : bigint,
  'videoId' : VideoId,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type VideoId = string;
export interface VocabEntry {
  'id' : bigint,
  'sourceVideoId' : VideoId,
  'englishText' : string,
  'savedAt' : Timestamp,
  'translationText' : string,
}
export interface WatchedVideo { 'watchedAt' : Timestamp, 'videoId' : VideoId }
export interface _SERVICE {
  'getAllUsers' : ActorMethod<[], Array<PublicUserProfile>>,
  'getIsAdmin' : ActorMethod<[string], boolean>,
  'getLeaderboard' : ActorMethod<[], Array<PublicUserProfile>>,
  'getQuizResults' : ActorMethod<[], Array<QuizResult>>,
  'getUserProfile' : ActorMethod<[], [] | [PublicUserProfile]>,
  'getVocabulary' : ActorMethod<[], Array<VocabEntry>>,
  'getWatchedVideos' : ActorMethod<[], Array<WatchedVideo>>,
  'markVideoWatched' : ActorMethod<[VideoId], undefined>,
  'saveQuizResult' : ActorMethod<[VideoId, bigint, bigint, bigint], undefined>,
  'saveVocabularyWord' : ActorMethod<[string, string, VideoId], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'setEmail' : ActorMethod<[string], undefined>,
  'setLanguagePreference' : ActorMethod<[Language], undefined>,
  'setProfileImage' : ActorMethod<[string], undefined>,
  'updateUserPoints' : ActorMethod<[bigint], undefined>,
  'updateUserStreak' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];