/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export interface WatchedVideo {
    watchedAt: Timestamp;
    videoId: VideoId;
}
export type Timestamp = bigint;
export interface PublicUserProfile {
    id: UserId;
    streak: bigint;
    displayName: string;
    profileImage: string;
    createdAt: Timestamp;
    email: string;
    language: Language;
    points: bigint;
}
export type VideoId = string;
export interface QuizResult {
    id: bigint;
    score: bigint;
    takenAt: Timestamp;
    totalQuestions: bigint;
    correctAnswers: bigint;
    videoId: VideoId;
}
export interface VocabEntry {
    id: bigint;
    sourceVideoId: VideoId;
    englishText: string;
    savedAt: Timestamp;
    translationText: string;
}
export enum Language {
    Uzbek = "Uzbek",
    Russian = "Russian"
}
export interface backendInterface {
    getAllUsers(): Promise<Array<PublicUserProfile>>;
    getIsAdmin(email: string): Promise<boolean>;
    getLeaderboard(): Promise<Array<PublicUserProfile>>;
    getQuizResults(): Promise<Array<QuizResult>>;
    getUserProfile(): Promise<PublicUserProfile | null>;
    getVocabulary(): Promise<Array<VocabEntry>>;
    getWatchedVideos(): Promise<Array<WatchedVideo>>;
    markVideoWatched(videoId: VideoId): Promise<void>;
    saveQuizResult(videoId: VideoId, score: bigint, correctAnswers: bigint, totalQuestions: bigint): Promise<void>;
    saveVocabularyWord(englishText: string, translationText: string, sourceVideoId: VideoId): Promise<void>;
    setDisplayName(displayName: string): Promise<void>;
    setEmail(email: string): Promise<void>;
    setLanguagePreference(language: Language): Promise<void>;
    setProfileImage(imageUrl: string): Promise<void>;
    updateUserPoints(points: bigint): Promise<void>;
    updateUserStreak(streak: bigint): Promise<void>;
}
import type { Language as _Language, PublicUserProfile as _PublicUserProfile, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllUsers(): Promise<Array<PublicUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIsAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getIsAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIsAdmin(arg0);
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<PublicUserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizResults(): Promise<Array<QuizResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResults();
            return result;
        }
    }
    async getUserProfile(): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVocabulary(): Promise<Array<VocabEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVocabulary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVocabulary();
            return result;
        }
    }
    async getWatchedVideos(): Promise<Array<WatchedVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchedVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchedVideos();
            return result;
        }
    }
    async markVideoWatched(arg0: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markVideoWatched(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markVideoWatched(arg0);
            return result;
        }
    }
    async saveQuizResult(arg0: VideoId, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuizResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveVocabularyWord(arg0: string, arg1: string, arg2: VideoId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVocabularyWord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVocabularyWord(arg0, arg1, arg2);
            return result;
        }
    }
    async setDisplayName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDisplayName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDisplayName(arg0);
            return result;
        }
    }
    async setEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEmail(arg0);
            return result;
        }
    }
    async setLanguagePreference(arg0: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setLanguagePreference(to_candid_Language_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setLanguagePreference(to_candid_Language_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setProfileImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfileImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfileImage(arg0);
            return result;
        }
    }
    async updateUserPoints(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPoints(arg0);
            return result;
        }
    }
    async updateUserStreak(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserStreak(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserStreak(arg0);
            return result;
        }
    }
}
function from_candid_Language_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PublicUserProfile_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): PublicUserProfile {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): PublicUserProfile | null {
    return value.length === 0 ? null : from_candid_PublicUserProfile_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    streak: bigint;
    displayName: string;
    profileImage: string;
    createdAt: _Timestamp;
    email: string;
    language: _Language;
    points: bigint;
}): {
    id: UserId;
    streak: bigint;
    displayName: string;
    profileImage: string;
    createdAt: Timestamp;
    email: string;
    language: Language;
    points: bigint;
} {
    return {
        id: value.id,
        streak: value.streak,
        displayName: value.displayName,
        profileImage: value.profileImage,
        createdAt: value.createdAt,
        email: value.email,
        language: from_candid_Language_n4(_uploadFile, _downloadFile, value.language),
        points: value.points
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Uzbek: null;
} | {
    Russian: null;
}): Language {
    return "Uzbek" in value ? Language.Uzbek : "Russian" in value ? Language.Russian : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PublicUserProfile>): Array<PublicUserProfile> {
    return value.map((x)=>from_candid_PublicUserProfile_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    Uzbek: null;
} | {
    Russian: null;
} {
    return value == Language.Uzbek ? {
        Uzbek: null
    } : value == Language.Russian ? {
        Russian: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
